//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackForITStudents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cauhoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cauhoi()
        {
            this.Tralois = new HashSet<Traloi>();
            this.Trangchus = new HashSet<Trangchu>();
        }
    
        public string Ma_cau_hoi { get; set; }
        public string Noidungcauhoi { get; set; }
        public string ID { get; set; }
        public bool Andanh { get; set; }
        public Nullable<System.DateTime> Thoigian { get; set; }
    
        public virtual Taikhoansinhvien Taikhoansinhvien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traloi> Tralois { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trangchu> Trangchus { get; set; }
    }
}
