//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackForITStudents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAUHOI()
        {
            this.TRALOIs = new HashSet<TRALOI>();
        }
    
        public int MaCH { get; set; }
        public string Noidung { get; set; }
        public bool Andanh { get; set; }
        public System.DateTime Thoigian { get; set; }
        public string Email { get; set; }
    
        public virtual TAIKHOANSV TAIKHOANSV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRALOI> TRALOIs { get; set; }
    }
}
