//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackForITStudents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAUHOIDADUYET
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAUHOIDADUYET()
        {
            this.THONGBAOs = new HashSet<THONGBAO>();
            this.TRALOIs = new HashSet<TRALOI>();
        }
    
        public int MaCHD { get; set; }
        public string Noidung { get; set; }
        public bool Andanh { get; set; }
        public System.DateTime Thoigian { get; set; }
        public string Email { get; set; }
        public string MaTKAsp { get; set; }
        public Nullable<bool> pin { get; set; }
        public Nullable<bool> Rep { get; set; }
        public Nullable<int> MaCD { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CHUDE CHUDE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THONGBAO> THONGBAOs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRALOI> TRALOIs { get; set; }
    }
}
