//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackForITStudents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONGBAO
    {
        public int MaTB { get; set; }
        public int MaCHD { get; set; }
        public int MaCTL { get; set; }
        public System.DateTime Thoigian { get; set; }
        public string NoidungTB { get; set; }
    
        public virtual CAUHOIDADUYET CAUHOIDADUYET { get; set; }
        public virtual TRALOI TRALOI { get; set; }
    }
}
