//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackForITStudents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traloi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Traloi()
        {
            this.Trangchus = new HashSet<Trangchu>();
        }
    
        public string Ma_Cau_Tra_Loi { get; set; }
        public Nullable<System.DateTime> Thoigian { get; set; }
        public string Ma_cau_hoi { get; set; }
        public string Ma_Tai_khoan { get; set; }
        public string Noidungcautraloi { get; set; }
    
        public virtual Cauhoi Cauhoi { get; set; }
        public virtual Taikhoan Taikhoan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trangchu> Trangchus { get; set; }
    }
}
