//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackForITStudents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trangchu
    {
        public string Ma_Trang_Chu { get; set; }
        public string ID { get; set; }
        public string Ma_Tai_khoan { get; set; }
        public string Ma_Cau_hoi { get; set; }
        public Nullable<bool> Thatim { get; set; }
        public string Ma_Cau_Tra_Loi { get; set; }
    
        public virtual Cauhoi Cauhoi { get; set; }
        public virtual Taikhoan Taikhoan { get; set; }
        public virtual Taikhoansinhvien Taikhoansinhvien { get; set; }
        public virtual Traloi Traloi { get; set; }
    }
}
